server:
  port: 0

spring:
  application:
    name: crack-hash-worker
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

crack-hash:
  rabbitmq:
    exchange:
      direct: ${RABBIT_DIRECT_EXCHANGE}
    route:
      manager: ${RABBIT_MANAGER_ROUTE}
      worker: ${RABBIT_WORKER_ROUTE}
    queue:
      manager: ${RABBIT_MANAGER_QUEUE}
      worker: ${RABBIT_WORKER_QUEUE}