server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  server:
    expected-client-renewal-interval-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false