server:
  port: 8080

spring:
  application:
    name: crack-hash-manager

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    should-enforce-registration-at-init: true

crack-hash:
  timeout-in-sec: ${TIMEOUT}