server:
  port: 8080

spring:
  application:
    name: crack-hash-manager
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}

crack-hash:
  number-of-task-parts: ${NUMBER_OF_TASK_PARTS:10}
  rabbitmq:
    exchange:
      direct: ${RABBIT_DIRECT_EXCHANGE}
    route:
      manager: ${RABBIT_MANAGER_ROUTE}
      worker: ${RABBIT_WORKER_ROUTE}
    queue:
      manager: ${RABBIT_MANAGER_QUEUE}
      worker: ${RABBIT_WORKER_QUEUE}